### ISSUE TITLE
scrapli send_command to junos device hangs with long string

### ISSUE THREAD

**Issue by vireakouk** [scrapli/nornir_scrapli#128]
Hi @carlmontanari @tejasmokashi1992 
First of all, thanks for creating this tool, it's extremely valuable to the network community. I'm facing an issue that would appreciate your time.

I have a typical case of login using ssh-gpg key which is a really long string, and I use send_command like the below:

```
    r = task.run(
        task = send_command, 
        name = ("Deploy user accounts"),
        command = task.host["commands"],
    )
    r = task.run(
        task = send_command,
        name = "Committing change.",
        command = "commit and-quit"
    )
```
where task.host["commands"] are a long string like below:

```
set system login user tester full-name tester
set system login user tester uid 1005
set system login user tester class super-user
set system login user tester authentication ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDxAZn1IQ2cBxIbgwksWOfkAMKKLa3cUYMkbQBaR9Nw4CfoLs8xiu0Kb8oN4JH6p+E4C1MrlmFQuMZbVzs9JseV2pe6kw0xKQgLINopyF6letzCOEzPH7THicxyQc35vMIa8JTAMU6X3hpzzSUVSQGKDljj+c4XayTZCVQVg2Yqc67Vdm+4q4OQCU7Fns73KWmqwsdYtuyk74yPWjAvKkEaW7I9d3TLKVI8LLdzC6FoP2jJyGEoqxWEf2yL0eWelmJi/ikLJFSdXvdVCzvyI3dTeNqEdaisKQ0SJ7W0ysH1Os2hYyxBazWonMYI/T8Sh9J21xcWGmBumFTIcsbLEP17tojR4ttFq69ebtJIMkbPo0e+u4gWdvM44MyWsDm8jkKDuqNcduGIhF0dFY57niq4TEv5+Yvya2gwqBS4ttq/NlUAseL4zAcaP+kpDae4GMiRXwpFAiKA3ctn6/gf5QLvcAHMz62ASHeo9gG9t6n0eGUzBD/lv0qMsaYgmxfgIpqoU6Sr1w2EVp8TYjIVAaO/96Kljb2v9mB+0/BTO7gxJicxUNYQLOhEYdMnbr0bFNAG93hlUiq5eGTTG7nn1mre2OHWyGB8fZN9EukbMeFicgFTxgl3ddQawjn1Qb6u//ZpSCD++IH4HQCjz1fI9r+yZ+6CqfUrM0PI+dwAfcL4pw== cardno:000500001BDE"
```
the script would hangs, but if I login to the target device, I can see that all commands went through but it hangs and won't get into the "commit and-quit" command step.

```
# show | compare
[edit system login]
+    user tester {
+        full-name tester;
+        uid 1005;
+        class super-user;
+        authentication {
+            ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDxAZn1IQ2cBxIbgwksWOfkAMKKLa3cUYMkbQBaR9Nw4CfoLs8xiu0Kb8oN4JH6p+E4C1MrlmFQuMZbVzs9JseV2pe6kw0xKQgLINopyF6letzCOEzPH7THicxyQc35vMIa8JTAMU6X3hpzzSUVSQGKDljj+c4XayTZCVQVg2Yqc67Vdm+4q4OQCU7Fns73KWmqwsdYtuyk74yPWjAvKkEaW7I9d3TLKVI8LLdzC6FoP2jJyGEoqxWEf2yL0eWelmJi/ikLJFSdXvdVCzvyI3dTeNqEdaisKQ0SJ7W0ysH1Os2hYyxBazWonMYI/T8Sh9J21xcWGmBumFTIcsbLEP17tojR4ttFq69ebtJIMkbPo0e+u4gWdvM44MyWsDm8jkKDuqNcduGIhF0dFY57niq4TEv5+Yvya2gwqBS4ttq/NlUAseL4zAcaP+kpDae4GMiRXwpFAiKA3ctn6/gf5QLvcAHMz62ASHeo9gG9t6n0eGUzBD/lv0qMsaYgmxfgIpqoU6Sr1w2EVp8TYjIVAaO/96Kljb2v9mB+0/BTO7gxJicxUNYQLOhEYdMnbr0bFNAG93hlUiq5eGTTG7nn1mre2OHWyGB8fZN9EukbMeFicgFTxgl3ddQawjn1Qb6u//ZpSCD++IH4HQCjz1fI9r+yZ+6CqfUrM0PI+dwAfcL4pw== cardno:000500001BDE"; ## SECRET-DATA
+        }
+    }

[edit]
```
I wonder if there is any setting or tweaks to make send_command work with long string.

**Comment by vireakouk** [comment]
to add, I'm using below connection options and have tried various combinations of timeout setting. 

```
juniper_junos:
  connection_options:
    scrapli:
      platform: juniper_junos
      extras:
        ssh_config_file: True
        auth_strict_key: False
        timeout_ops: 180
        timeout_transport: 180
        timeout_socket: 180
```

**Comment by carlmontanari** [comment]
Hey @vireakouk 

Thanks for opening this and the details! This is a "feature not a bug" :laughing:! Kinda kidding, but also that is kinda true! Basically when we log in to the device we usually (and this is true of Junos) send some terminal width command to set terminal width. It looks like the Junos default "screen-width" value is 511 -- when the terminal hits that character count it "wraps" which basically means it sends a bunch of ansi magic characters to do backspaces on the terminal so when you are a human looking at it you see the rest of what you are typing out. 

This wrapping behavior breaks the default way scrapli operates -- that is, we always write users input and we never ever send the "return" until we are able to read the users input in its entirety. We do this to basically prevent any "runaway" commands where we just keep sending commands so fast and the device ends up barfing on that/getting out of "sync".

You've got two primary options to handle this:

1.  set a wider terminal screen width if possible -- I am pretty sure its set to 511 as that is kind of the lowest common denominator width Junos supports. but if your platform supports higher, you can of course crank that up as high as it'll go. you could do this with just a send_command task prior to sending the long string.
2. you can "reach into" the channel and directly write the input -- I dont stay up to date on nornir, but this would involve you going into the nornir bits to access the underlying scrapli connection object itself and doing something like: `conn.channel.write("my really long line")` where `conn` of course is the scrapli connection.

HTH

**Comment by carlmontanari** [comment]
Oh yeah -- another option could be to use scrapli_cfg load config task -- in that mode we write the command to a file using the root shell, then load it into the config -- I am fairly sure that we would not have the terminal wrapping situation there (though I could be wrong!)

**Comment by vireakouk** [comment]
Hi @carlmontanari 
thanks so much for your response. I just tried option 1 as you suggested by setting `set cli screen-width 0` and `set cli screen-width 1024`. Both still hang. So the only workable option is to use `scrapli_cfg` load. I generally don't prefer the cfg load option, but for just user account that would do.

**Comment by carlmontanari** [comment]
Ah ok at least we have a working path. If you could snag logs ([this](https://github.com/carlmontanari/scrapli/blob/master/examples/logging/opinionated_logging.py) should work in conjunction w/ nornir I believe and still get ya logs -- just make sure to target one host so its readable) we can try to see whats going on.

**Comment by vireakouk** [comment]
thanks. I'll try that some time later.
