### ISSUE TITLE
GenericDriver `send_command` empties lines ending with `]` in nornir results

### ISSUE THREAD

**Issue by bortok** [scrapli/nornir_scrapli#132]
In `send_command` output, if a line ends with `]` , it is being returned as an empty line in nornir results.

How to reproduce: run the following command on a linux target: `"echo line; echo ]; echo end"`

This breaks `ip -json -p address show` output, as it ends with `]`. On Juniper cRPD docker container the `-p` flag is always on. As a result, I can't collect IP address info from such nodes.

**Comment by carlmontanari** [comment]
hey Alex!

can you snag logs please? my initial reaction is that this is probably more related to the default prompt pattern on the generic driver than anything else, but I could be wrong.

super quick test against a bsd box I have running at home looks like things work fine -- unless there is something nornir scrapli specific going on here, if so defo let me know, but for now im assuming this would be a "normal" scrapli issue.

```python
>>> conn = GenericDriver(host="blah", auth_password="blah", ssh_config_file=True, auth_strict_key=False)
>>> conn.open()
>>> conn.send_command("echo line; echo ]; echo end")
Response(host='nas',channel_input='echo line; echo ]; echo end',textfsm_platform='',genie_platform='',failed_when_contains=None)
>>> resp = conn.send_command("echo line; echo ]; echo end")
>>> resp.result
'line\n]\nend\n#
```

**Comment by bortok** [comment]
Hi Carl, sure, here is the setup and logs

`sudo clab dep -t ubuntu-host.yml`:
```Yaml
name: host

topology:
  nodes:
    host1:
      kind: linux
      image: netreplica/ubuntu-host:1.1
      cmd: /start.sh -S
      exec:
        - bash -c "echo root:root | chpasswd"
```

`getdata.py`
```Python
import time
from scrapli.driver import GenericDriver

def main():
    conn = GenericDriver(host="clab-host-host1", auth_username="root", auth_password="root", ssh_config_file=False, auth_strict_key=False, channel_log=True)
    conn.open()
    resp = conn.send_command("echo line; echo ]; echo end")
    print(resp.result)

if __name__ == "__main__":
    main()
```

Console output:
```Shell
$ time python3 getdata.py
line

end

real	0m0.366s
user	0m0.153s
sys	0m0.025s
```

`scrapli_channel.log`

```Shell
$ cat scrapli_channel.log
Warning: Permanently added 'clab-host-host1,2001:172:20:20::2' (ECDSA) to the list of known hosts.
root@clab-host-host1's password:
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.11.0-46-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.
Last login: Mon Sep 19 18:57:39 2022 from 2001:172:20:20::1
root@host1:~# echo line; echo ]; echo end
line
]
end
```

**Comment by carlmontanari** [comment]
Awesome thanks Alex, will check it out this weekend prolly and get back to ya!

**Comment by carlmontanari** [comment]
Hey sorry for the delay but happily this is an easy one!

The default pattern for the prompt for generic driver is *super* broad and it catches that `]` as a valid prompt. So scrapli chomps that out and you are left with the missing char. Easy fix is to just modify the prompt pattern to something that'll work for that box, I Just tested with `comms_prompt_pattern=r".*:~#"` and get the full output. Of course you may need to play with that a bit. In general I like the prompt patterns to be as restrictive as possible, but obviously they'll need to accommodate any kind of changes the prompt may have.

Lemme know if that sorts this out for ya!

Carl

**Comment by bortok** [comment]
Hi Carl, thanks for looking into this. The solution you provided works. Tested with `ubuntu` and `cRPD` container images. Here is the modified `getdata.py`:

```Python
import time
from scrapli.driver import GenericDriver

def main():
    conn = GenericDriver(host="clab-host-host1",
                          auth_username="root",
                          auth_password="root",
                          comms_prompt_pattern=r".*:~#",
                          ssh_config_file=False,
                          auth_strict_key=False,
                          channel_log=True)
    conn.open()
    resp = conn.send_command("echo line; echo ]; echo end")
    print(resp.result)

if __name__ == "__main__":
    main()
```

It returns:

```
line
]
end

real	0m0.390s
user	0m0.155s
sys	0m0.016s
```
