### ISSUE TITLE
Missing functions package after installation from pypi

### ISSUE THREAD

**Issue by vkoprivica** [scrapli/nornir_scrapli#138]
In version 2023.1.30  missing functions package after installation from pypi.

**Comment by carlmontanari** [comment]
ha, looks like worse than that, nothing but top level package... pyproject.toml screw up. updating shortly.

**Comment by carlmontanari** [comment]
2023.1.30.post1 should sort it, sorry about that. holler if there's something still messed up!

**Comment by vkoprivica** [comment]
Np, we found the way around that. All good.
