### ISSUE TITLE
How to commit configuration for cli session

### ISSUE THREAD

**Issue by dmulyalin** [scrapli/nornir_scrapli#37]
Hi,

Tried to apply config to IOS XR device using SSH (not NETCONF), can see in the logs that config was sent, but does not look like it was commited. Went to device to check as well - no config was applied.

**Comment by carlmontanari** [comment]
Hello!

You will need to send the commit yourself (or w/e is appropriate for the platform). Scrapli won't exit config mode so you can send a commit in another send_config task and/or use send_interact if you need to deal w/ prompting or anything like that.

Just realized I did *not* have discussions enabled for this repo, so I just enabled them. If that doesn't clear things up would you mind opening a thing in discussions so we can track this there? I have terrible anxiety/ocd about issues open so I'm trying to reserve issues specifically for bugs :D 

Thanks!
Carl

**Comment by dmulyalin** [comment]
Ok, 

Tested with sending `commit` and `exit` commands, works fine, have not thought about it by myself. 

Thank you for prompt response.

**Comment by carlmontanari** [comment]
Awesome! you don’t need to send “exit” yourself, if you have a subsequent command (or just close the connection) it (scrapli) will auto acquire the right priv level for ya!
